
version: '3.8'

volumes:
  certbot-conf:
  certbot-www:

networks:
  backend:
    driver: bridge

services:
  guacd:
    image: guacamole/guacd:1.6.0
    container_name: guacd
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      - LOG_LEVEL=debug
      - GUACD_SSL=false
    volumes:
      - ./drive:/drive
      - ./recordings:/recordings
      - /dev/net/tun:/dev/net/tun
    command: ["-L", "debug"]

  guacamole:
    build: .
    container_name: guacamole
    restart: unless-stopped
    networks:
      - backend
    environment:
      - GUACD_HOSTNAME=172.17.0.1
      - GUACD_PORT=4822
    depends_on:
      - guacd

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    platform: linux/arm64
    container_name: nginx
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "880:80"
      - "8443:443"
    volumes:
      - certbot-conf:/etc/letsencrypt:ro
      - certbot-www:/var/www/certbot:ro
    depends_on:
      certbot-init:
        condition: service_completed_successfully
      guacamole:
        condition: service_started

  certbot-init:
    image: certbot/certbot
    container_name: certbot-init
    networks:
      - backend
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email dennislewin@gmx.de --agree-tos --no-eff-email -d home.dl-dev.de --non-interactive

  certbot-renew:
    image: certbot/certbot
    container_name: certbot-renew
    networks:
      - backend
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; chmod -R 755 /etc/letsencrypt; sleep 12h & wait $${!}; done;'"
    depends_on:
      certbot-init:
        condition: service_completed_successfully
      nginx:
        condition: service_started
