
version: '3.8'

volumes:
  guacamole_config:

networks:
  backend:
    driver: bridge

services:
  guacd:
    image: guacamole/guacd:1.6.0
    restart: unless-stopped
    networks:
      - backend
    environment:
      - GUACD_LOG_LEVEL=debug
    command: ["-L", "debug"]

  guacamole:
    image: guacamole/guacamole:1.6.0
    restart: unless-stopped
    networks:
      - backend
    environment:
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
    volumes:
      - guacamole_config:/etc/guacamole
    depends_on:
      - guacd

  nginx:
    image: nginx:latest
    platform: linux/arm64
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "880:80"
      - "8443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - guacamole
