
version: '3.8'

services:
  guacd:
    image: guacamole/guacd:1.6.0
    container_name: guacd
    restart: unless-stopped
    ports:
      - "4822:4822"

  guacamole:
    build: .
    container_name: guacamole-web
    restart: unless-stopped
    depends_on:
      - guacd
    volumes:
      - ./guac-config:/etc/guacamole

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    platform: linux/arm64
    container_name: guacamole-nginx
    restart: unless-stopped
    ports:
      - "880:80"
      - "8443:443"
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - guacamole

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot
      --email dennislewin@gmx.de --agree-tos --no-eff-email
      -d home.dl-dev.de"
