
version: '3.8'

volumes:
  certbot-conf:
  certbot-www:

networks:
  backend:
    driver: bridge

services:
  guacd:
    image: guacamole/guacd:1.6.0
    container_name: guacd
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "4822:4822"

  guacamole-web:
    build: .
    container_name: guacamole-web
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - guacd
    volumes:
      - ./guac-config:/etc/guacamole

  guacamole-nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    platform: linux/arm64
    container_name: guacamole-nginx
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "880:80"
      - "8443:443"
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - guacamole-web

  certbot:
    image: certbot/certbot
    container_name: certbot
    networks:
      - backend
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot
      --email dennislewin@gmx.de --agree-tos --no-eff-email
      -d home.dl-dev.de"
